package StudentApp;


/**
* StudentApp/_StudentInfoImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test.idl
* 18 April 2018 19:09:06 o'clock IST
*/

public abstract class _StudentInfoImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements StudentApp.StudentInfo, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _StudentInfoImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("totalGrade", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // StudentApp/StudentInfo/totalGrade
       {
         StudentApp.StudentHolder stu = new StudentApp.StudentHolder ();
         stu.value = StudentApp.StudentHelper.read (in);
         int $result = (int)0;
         $result = this.totalGrade (stu);
         out = $rh.createReply();
         out.write_long ($result);
         StudentApp.StudentHelper.write (out, stu.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:StudentApp/StudentInfo:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _StudentInfoImplBase
