package StudentApp;


/**
* StudentApp/StudentInfoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test.idl
* 18 April 2018 19:09:06 o'clock IST
*/

public interface StudentInfoOperations 
{
  int totalGrade (StudentApp.StudentHolder stu);
} // interface StudentInfoOperations
