package StudentApp;


/**
* StudentApp/Student.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test.idl
* 18 April 2018 19:09:06 o'clock IST
*/

public final class Student implements org.omg.CORBA.portable.IDLEntity
{
  public int grade1 = (int)0;
  public int grade2 = (int)0;

  public Student ()
  {
  } // ctor

  public Student (int _grade1, int _grade2)
  {
    grade1 = _grade1;
    grade2 = _grade2;
  } // ctor

} // class Student
