package StudentApp;

/**
* StudentApp/StudentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test.idl
* 18 April 2018 19:09:06 o'clock IST
*/

public final class StudentHolder implements org.omg.CORBA.portable.Streamable
{
  public StudentApp.Student value = null;

  public StudentHolder ()
  {
  }

  public StudentHolder (StudentApp.Student initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StudentApp.StudentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StudentApp.StudentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StudentApp.StudentHelper.type ();
  }

}
