package StudentApp;

/**
* StudentApp/StudentInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test.idl
* 18 April 2018 19:09:06 o'clock IST
*/

public final class StudentInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public StudentApp.StudentInfo value = null;

  public StudentInfoHolder ()
  {
  }

  public StudentInfoHolder (StudentApp.StudentInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StudentApp.StudentInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StudentApp.StudentInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StudentApp.StudentInfoHelper.type ();
  }

}
