package StudentApp;


/**
* StudentApp/StudentHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test.idl
* 18 April 2018 19:09:06 o'clock IST
*/

abstract public class StudentHelper
{
  private static String  _id = "IDL:StudentApp/Student:1.0";

  public static void insert (org.omg.CORBA.Any a, StudentApp.Student that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static StudentApp.Student extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "grade1",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "grade2",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (StudentApp.StudentHelper.id (), "Student", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static StudentApp.Student read (org.omg.CORBA.portable.InputStream istream)
  {
    StudentApp.Student value = new StudentApp.Student ();
    value.grade1 = istream.read_long ();
    value.grade2 = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, StudentApp.Student value)
  {
    ostream.write_long (value.grade1);
    ostream.write_long (value.grade2);
  }

}
